FROM quay.io/centos/centos:stream8

RUN echo "2022-08-19" > /build_time

RUN dnf -y install --setopt=install_weak_deps=False \
        python3 make rust-toolset gcc python3-pytest && \
    ln -s /usr/bin/pytest-3 /usr/bin/pytest && \
    dnf clean all
